# Generated by Django 4.2.1 on 2023-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('timeStamp', models.DateField(blank=True)),
            ],
        ),
    ]
